### ISSUE TITLE
BinaryTree - array

### ISSUE THREAD

**Issue by Joyykim** [ai-creatv/algorithm_PBS13#12]
array를 기반으로한 BT의 DFS구현입니다. found 변수를 쓰지 않고 구현해봤는데 리뷰해주신다면 감사하겠습니다!!
https://github.com/Joyykim/algorithm/blob/master/binary_tree_array.py#L63

**Comment by ai-creatv** [comment]
재미있고 깔끔한 구현이네요!

True가 한번이라도 발생하면 나머지는 연산하지 않는 특징을 이용해서 분기를 단순화한 점이 좋은 것 같습니다.

코드를 많이 단순화 하셨기 때문에, 처음 보는 사람이 더 쉽게 이해 하려면 left와 right 변수 정도는 사용해도 좋을 것 같습니다 :)

**Comment by Joyykim** [comment]
> 재미있고 깔끔한 구현이네요!
> 
> True가 한번이라도 발생하면 나머지는 연산하지 않는 특징을 이용해서 분기를 단순화한 점이 좋은 것 같습니다.
> 
> 코드를 많이 단순화 하셨기 때문에, 처음 보는 사람이 더 쉽게 이해 하려면 left와 right 변수 정도는 사용해도 좋을 것 같습니다 :)

리뷰 감사합니다!!
