### ISSUE TITLE
homework_1 LevelTest_1

### ISSUE THREAD

**Issue by bunnycast** [ai-creatv/algorithm_PBS13#3]
https://github.com/bunnycast/algorithm/tree/master/homework_1

**Comment by ai-creatv** [comment]
수고하셨습니다!

set 자료구조를 이용해서 잘 구현해 주셨네요 👍 

컨벤션에 크게 어긋나는 부분 없이 잘 구현해 주셨습니다.

단, sum은 내장함수 sum()과 겹치기 때문에, 다른 이름을 쓰는 것이 더 좋은 점 확인해 주세요 :)
