### ISSUE TITLE
homework_1: programmers lv1 test

### ISSUE THREAD

**Issue by hsw0905** [ai-creatv/algorithm_PBS13#4]
https://github.com/hsw0905/datastructure/tree/homework_1/programmers/lv1

**Comment by ai-creatv** [comment]
수고하셨습니다!

1번 문제의 경우, answer = False로 변경하는 곳에서 return False를 하시면 최적화가 더 좋아집니다 :)

2번 문제의 경우 elif 대신 else를 쓰시는 것이 더 좋습니다.

elif와 else가 동작이 동일하지만, elif를 쓸 경우 코드를 처음 읽는 사람은 if문에 걸리지 않아 answer=''로 출력되는 경우가 있지 않은지 따져보아야 합니다.
