### ISSUE TITLE
homework_2 : doubly linked list

### ISSUE THREAD

**Issue by hsw0905** [ai-creatv/algorithm_PBS13#5]
https://github.com/hsw0905/datastructure/tree/homework_2/list

**Comment by ai-creatv** [comment]
잘 구현해 주셨습니다. 수고하셨습니다! 👍 

- append의 경우, head에서 찾아갈 필요 없이 곧바로 tail을 이용해 O(1)로 구현 가능합니다.
- remove와 insert의 경우, prev를 유지할 필요가 없이, curr.prev를 이용해 알고리즘 구현이 가능합니다.
- reverse_print를 구현하여 양방향으로 잘구현됐는지 확인해 주신 점 훌륭합니다 :)
