### ISSUE TITLE
homework_3 : Linked_queue

### ISSUE THREAD

**Issue by hsw0905** [ai-creatv/algorithm_PBS13#9]
[Linked Queue](https://github.com/hsw0905/datastructure/blob/queue/queue/linked_queue.py)

**Comment by ai-creatv** [comment]
깔끔하게 잘 구현해 주셨습니다 :)

단, 자료가 1개만 있을 때 get한 경우 tail도 None으로 초기화해주어야 하는 점 확인해주세요!

상속과 nested 클래스를 이용한 구현도 확인해서 숙지해주세요!
